//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras_detalle
    {
        public string auto_documento { get; set; }
        public string auto_producto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string auto_departamento { get; set; }
        public string auto_grupo { get; set; }
        public string auto_subgrupo { get; set; }
        public string auto_deposito { get; set; }
        public decimal cantidad { get; set; }
        public string empaque { get; set; }
        public decimal descuento1p { get; set; }
        public decimal descuento2p { get; set; }
        public decimal descuento3p { get; set; }
        public decimal descuento1 { get; set; }
        public decimal descuento2 { get; set; }
        public decimal descuento3 { get; set; }
        public decimal total_neto { get; set; }
        public decimal tasa { get; set; }
        public decimal impuesto { get; set; }
        public decimal total { get; set; }
        public string auto { get; set; }
        public string estatus_anulado { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo { get; set; }
        public string deposito { get; set; }
        public int signo { get; set; }
        public string auto_proveedor { get; set; }
        public string decimales { get; set; }
        public int contenido_empaque { get; set; }
        public decimal cantidad_und { get; set; }
        public decimal costo_und { get; set; }
        public string codigo_deposito { get; set; }
        public string detalle { get; set; }
        public string auto_tasa { get; set; }
        public string categoria { get; set; }
        public decimal costo_promedio_und { get; set; }
        public decimal costo_compra { get; set; }
        public string codigo_proveedor { get; set; }
        public decimal cantidad_bono { get; set; }
        public decimal costo_bruto { get; set; }
        public string estatus_unidad { get; set; }
        public System.DateTime fecha_lote { get; set; }
        public string cierre_ftp { get; set; }
    
        public virtual compras compras { get; set; }
        public virtual empresa_depositos empresa_depositos { get; set; }
        public virtual empresa_tasas empresa_tasas { get; set; }
        public virtual productos productos { get; set; }
        public virtual productos_grupo productos_grupo { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
