//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras_pend_detalle
    {
        public int id { get; set; }
        public int idPend { get; set; }
        public string prd_auto { get; set; }
        public string prd_codigo { get; set; }
        public string prd_nombre { get; set; }
        public string depart_auto { get; set; }
        public string grupo_auto { get; set; }
        public string subg_auto { get; set; }
        public string tasa_auto { get; set; }
        public decimal cant_fact { get; set; }
        public decimal precio_fact { get; set; }
        public string empaque_nombre { get; set; }
        public int empaque_cont { get; set; }
        public string empaque_unidad { get; set; }
        public decimal dsct_1_fact { get; set; }
        public decimal dsct_2_fact { get; set; }
        public decimal dsct_3_fact { get; set; }
        public string prd_categoria { get; set; }
        public string prd_decimales { get; set; }
        public decimal tasa_iva { get; set; }
        public string codrefprv_fact { get; set; }
        public decimal precio_fact_divisa { get; set; }
        public decimal costoActual_local { get; set; }
        public decimal costoActual_divisa { get; set; }
        public string admDivisa { get; set; }
        public string empaque_auto { get; set; }
        public string empaque_decimales { get; set; }
        public string empaque_predeterminado_compra { get; set; }
        public string empaque_seleccionado_id { get; set; }
    
        public virtual compras_pend compras_pend { get; set; }
    }
}
