//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxp
    {
        public string auto { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_documento { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public string nota { get; set; }
        public decimal importe { get; set; }
        public decimal acumulado { get; set; }
        public string auto_proveedor { get; set; }
        public string proveedor { get; set; }
        public string ci_rif { get; set; }
        public string codigo_proveedor { get; set; }
        public string estatus_cancelado { get; set; }
        public decimal resta { get; set; }
        public string estatus_anulado { get; set; }
        public string auto_documento { get; set; }
        public string numero { get; set; }
        public string auto_agencia { get; set; }
        public string agencia { get; set; }
        public int signo { get; set; }
        public int dias { get; set; }
        public string auto_asiento { get; set; }
        public string anexo { get; set; }
        public string estatus_cierre_contable { get; set; }
        public decimal importeDivisa { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
