//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class compraEntities : DbContext
    {
        public compraEntities()
            : base("name=compraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empresa_depositos> empresa_depositos { get; set; }
        public virtual DbSet<empresa_sucursal> empresa_sucursal { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<empresa_departamentos> empresa_departamentos { get; set; }
        public virtual DbSet<empresa_grupo> empresa_grupo { get; set; }
        public virtual DbSet<empresa_tasas> empresa_tasas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productos_grupo> productos_grupo { get; set; }
        public virtual DbSet<productos_marca> productos_marca { get; set; }
        public virtual DbSet<productos_medida> productos_medida { get; set; }
        public virtual DbSet<productos_proveedor> productos_proveedor { get; set; }
        public virtual DbSet<proveedores_grupo> proveedores_grupo { get; set; }
        public virtual DbSet<sistema_configuracion> sistema_configuracion { get; set; }
        public virtual DbSet<sistema_estados> sistema_estados { get; set; }
        public virtual DbSet<proveedores_agencias> proveedores_agencias { get; set; }
        public virtual DbSet<compras_pend> compras_pend { get; set; }
        public virtual DbSet<productos_conceptos> productos_conceptos { get; set; }
        public virtual DbSet<productos_conteo> productos_conteo { get; set; }
        public virtual DbSet<productos_costos> productos_costos { get; set; }
        public virtual DbSet<productos_deposito> productos_deposito { get; set; }
        public virtual DbSet<productos_ext> productos_ext { get; set; }
        public virtual DbSet<productos_precios> productos_precios { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<compras_detalle> compras_detalle { get; set; }
        public virtual DbSet<compras_pend_detalle> compras_pend_detalle { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<cxp> cxp { get; set; }
        public virtual DbSet<productos_kardex> productos_kardex { get; set; }
    }
}
