//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_conteo
    {
        public string auto { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string codigo_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string auto_usuario { get; set; }
        public string codigo_deposito { get; set; }
        public string nombre_deposito { get; set; }
        public string auto_deposito { get; set; }
        public string auto_producto { get; set; }
        public string nombre_producto { get; set; }
        public string codigo_producto { get; set; }
        public decimal teorico { get; set; }
        public decimal fisico { get; set; }
        public decimal resultado { get; set; }
        public string origen { get; set; }
        public string estatus_anulado { get; set; }
        public string nota { get; set; }
        public int edad { get; set; }
        public string estatus_resuelto { get; set; }
    }
}
