//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_ext
    {
        public string auto_producto { get; set; }
        public string auto_precio_may_1 { get; set; }
        public string auto_precio_may_2 { get; set; }
        public string auto_precio_may_3 { get; set; }
        public int contenido_may_1 { get; set; }
        public int contenido_may_2 { get; set; }
        public int contenido_may_3 { get; set; }
        public decimal utilidad_may_1 { get; set; }
        public decimal utilidad_may_2 { get; set; }
        public decimal utilidad_may_3 { get; set; }
        public decimal precio_may_1 { get; set; }
        public decimal precio_may_2 { get; set; }
        public decimal precio_may_3 { get; set; }
        public decimal pdmf_1 { get; set; }
        public decimal pdmf_2 { get; set; }
        public decimal pdmf_3 { get; set; }
        public string auto_precio_may_4 { get; set; }
        public Nullable<int> cont_may_4 { get; set; }
        public Nullable<decimal> utilidad_may_4 { get; set; }
        public Nullable<decimal> precio_may_4 { get; set; }
        public Nullable<decimal> pdmf_4 { get; set; }
        public string auto_emp_inv_1 { get; set; }
        public int cont_emp_inv_1 { get; set; }
        public string auto_precio_dsp_1 { get; set; }
        public int cont_dsp_1 { get; set; }
        public decimal utilidad_dsp_1 { get; set; }
        public decimal precio_dsp_1 { get; set; }
        public decimal pdivisafull_dsp_1 { get; set; }
        public string auto_precio_dsp_2 { get; set; }
        public int cont_dsp_2 { get; set; }
        public decimal utilidad_dsp_2 { get; set; }
        public decimal precio_dsp_2 { get; set; }
        public decimal pdivisafull_dsp_2 { get; set; }
        public string auto_precio_dsp_3 { get; set; }
        public int cont_dsp_3 { get; set; }
        public decimal utilidad_dsp_3 { get; set; }
        public decimal precio_dsp_3 { get; set; }
        public decimal pdivisafull_dsp_3 { get; set; }
        public string auto_precio_dsp_4 { get; set; }
        public int cont_dsp_4 { get; set; }
        public decimal utilidad_dsp_4 { get; set; }
        public decimal precio_dsp_4 { get; set; }
        public decimal pdivisafull_dsp_4 { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual productos_medida productos_medida { get; set; }
        public virtual productos_medida productos_medida1 { get; set; }
        public virtual productos_medida productos_medida2 { get; set; }
        public virtual productos_medida productos_medida3 { get; set; }
        public virtual productos_medida productos_medida4 { get; set; }
        public virtual productos_medida productos_medida5 { get; set; }
        public virtual productos_medida productos_medida6 { get; set; }
        public virtual productos_medida productos_medida7 { get; set; }
        public virtual productos_medida productos_medida8 { get; set; }
    }
}
